# Generated by Django 5.2.12 on 2026-03-26 04:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurableObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('folder', 'Folder'), ('file', 'File')], max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_objects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('securableobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='file.securableobject')),
                ('file_size', models.BigIntegerField()),
                ('mime_type', models.CharField(max_length=127)),
                ('sha256_hash', models.CharField(max_length=64)),
            ],
            bases=('file.securableobject',),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('action', models.CharField(max_length=50)),
                ('outcome', models.CharField(max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('securable_object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='file.securableobject')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ObjectPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.IntegerField()),
                ('ancestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descendant_links', to='file.securableobject')),
                ('descendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ancestor_links', to='file.securableobject')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('principal_id', models.UUIDField()),
                ('principal_type', models.CharField(choices=[('user', 'User'), ('role', 'Role')], max_length=10)),
                ('allow_mask', models.IntegerField(default=0)),
                ('deny_mask', models.IntegerField(default=0)),
                ('inheritance_flags', models.CharField(default='', max_length=10)),
                ('securable_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acls', to='file.securableobject')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('parent_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subroles', to='file.role')),
            ],
        ),
        migrations.CreateModel(
            name='FileVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_num', models.IntegerField()),
                ('storage_path', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('file_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='file.file')),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('securableobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='file.securableobject')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='file.folder')),
            ],
            bases=('file.securableobject',),
        ),
        migrations.AddIndex(
            model_name='securableobject',
            index=models.Index(fields=['deleted_at', 'type'], name='file_secura_deleted_b84b7d_idx'),
        ),
        migrations.AddConstraint(
            model_name='objectpath',
            constraint=models.UniqueConstraint(fields=('ancestor', 'descendant'), name='unique_object_path'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['securable_object', 'principal_id'], name='file_permis_securab_49f1fe_idx'),
        ),
    ]
