# Generated by Django 3.1.7 on 2026-03-26 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folder',
            options={'verbose_name': 'Folder'},
        ),
        migrations.RemoveField(
            model_name='folder',
            name='parent',
        ),
        migrations.AddField(
            model_name='securableobject',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='file.folder'),
        ),
        migrations.AlterField(
            model_name='objectpath',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
