# Generated by Django 5.2.12 on 2026-03-27 02:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_auto_20260326_0453'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'group_memberships',
            },
        ),
        migrations.RemoveField(
            model_name='role',
            name='parent_role',
        ),
        migrations.RenameIndex(
            model_name='permission',
            new_name='permissions_object__0e6a0d_idx',
            old_name='file_permis_securab_49f1fe_idx',
        ),
        migrations.RenameIndex(
            model_name='securableobject',
            new_name='objects_deleted_a3bf72_idx',
            old_name='file_secura_deleted_b84b7d_idx',
        ),
        migrations.RemoveField(
            model_name='securableobject',
            name='parent',
        ),
        migrations.AddField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='file.folder'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='securable_object',
            field=models.ForeignKey(db_column='object_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='file.securableobject'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='mime_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='securableobject_ptr',
            field=models.OneToOneField(db_column='object_id', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='file_detail', serialize=False, to='file.securableobject'),
        ),
        migrations.AlterField(
            model_name='file',
            name='sha256_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fileversion',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='fileversion',
            name='file_object',
            field=models.ForeignKey(db_column='object_id', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='file.file'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='securableobject_ptr',
            field=models.OneToOneField(db_column='object_id', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='folder_detail', serialize=False, to='file.securableobject'),
        ),
        migrations.AlterField(
            model_name='objectpath',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='principal_type',
            field=models.CharField(choices=[('user', 'User'), ('group', 'Group')], max_length=10),
        ),
        migrations.AlterField(
            model_name='permission',
            name='securable_object',
            field=models.ForeignKey(db_column='object_id', on_delete=django.db.models.deletion.CASCADE, related_name='acls', to='file.securableobject'),
        ),
        migrations.AlterModelTable(
            name='auditlog',
            table='audit_logs',
        ),
        migrations.AlterModelTable(
            name='file',
            table='files',
        ),
        migrations.AlterModelTable(
            name='fileversion',
            table='file_versions',
        ),
        migrations.AlterModelTable(
            name='folder',
            table='folders',
        ),
        migrations.AlterModelTable(
            name='objectpath',
            table='object_paths',
        ),
        migrations.AlterModelTable(
            name='permission',
            table='permissions',
        ),
        migrations.AlterModelTable(
            name='securableobject',
            table='objects',
        ),
        migrations.AddField(
            model_name='group',
            name='parent_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subgroups', to='file.group'),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='file.group'),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.AddConstraint(
            model_name='groupmembership',
            constraint=models.UniqueConstraint(fields=('user', 'group'), name='unique_group_membership'),
        ),
    ]
