# Generated by Django 5.2.12 on 2026-03-27 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_group_groupmembership_remove_role_parent_role_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='permission',
            constraint=models.UniqueConstraint(fields=('securable_object', 'principal_id', 'principal_type'), name='unique_object_principal_permission'),
        ),
    ]
